_BASE_: oneformer_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2DiNAT"
  DiNAT:
    EMBED_DIM: 192
    MLP_RATIO: 2.0
    DEPTHS: [3, 4, 18, 5]
    NUM_HEADS: [6, 12, 24, 48]
    KERNEL_SIZE: 11
    DROP_PATH_RATE: 0.3
    DILATIONS: [[1, 20, 1], [1, 5, 1, 10], [1, 2, 1, 3, 1, 4, 1, 5, 1, 2, 1, 3, 1, 4, 1, 5, 1, 5], [1, 2, 1, 2, 1]]
  WEIGHTS: "outputs/basketball_dinat_size/model_final.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  ONE_FORMER:
    NUM_OBJECT_QUERIES: 150
SOLVER:
  STEPS: (7555, 8101)
  MAX_ITER: 9375
  AMP:
    ENABLED: False
  CHECKPOINT_PERIOD: 500
TEST:
  DETECTIONS_PER_IMAGE: 150